### ISSUE TITLE
Should I do any preprocess before deformation?

### ISSUE THREAD

**Issue by crylingya** [WanquanF/RMA-Net#7]
Thanks for your excellent work and nice code!

I have downloaded the code and checkpoint, and tested it one the samples you gave. I got very good results, then I hoped to test my own files. 

I used the SMPL model to generate two poses of the same 'person' (they were set in the same coordinate system), and tested it with the model you trained, but the results were very strange. What prerequisites does this method have for the input data? Should I do any preprocess before deformation?

![Screenshot from 2021-10-13 19-42-57](https://user-images.githubusercontent.com/92097951/137185680-417fdc73-19df-4d6f-acad-bbee7e6f41d6.png)

**Comment by WanquanF** [comment]
This result looks really strange. I suggest that you compare your testing point cloud with the data in our dataset to see if the range of coordinates is consistent.
