### ISSUE TITLE
Deformation problem

### ISSUE THREAD

**Issue by daisyranc** [WanquanF/RMA-Net#8]
Thanks for your excellent work!

I had some problems when I tried to test RMA-Net on my own data (synthetic data generated from the SMPL model). I have checked my input data (source & target) were stay in a similar coordinate system but different size as your sample data. My result didn't look as good as you show. I have tried to use your sample data, and the results were all perfect. How should I do to get a better result? or if your method has some limitations (maybe it is not suitable for arbitrary body registration)?
![1](https://user-images.githubusercontent.com/72395942/140730771-6340baeb-b53d-4f2f-a958-48ed486252de.PNG)
(The red point cloud is the source, the blue one is the target and the green one is the result from RMA-Net)
![2](https://user-images.githubusercontent.com/72395942/140732542-d6a1b70b-a272-4825-b6b4-9e5c18039134.PNG)
(The yellow one is my data and another one is your sample data. I am not sure if they are in the same coordinate system but they look similar. )

**Comment by WanquanF** [comment]
If you want to test on your own data, I suggest not using the pre-trained model directly. There may be many reasons for the poor performance: the difference in vertex density or uniformity, or some other reasons that cause the difference between your data and the data in the training set. You can retrain on your own data (this is easy. If you only test SMPL models, you can even employ a supervised training strategy).
